### ISSUE TITLE
맥주 검색에서 아무 필터도 사용하지 않은 경우 전체 맥주가 리스트되도록 수정

### ISSUE THREAD

**Issue by devyoujin** [beerlot/beerlot-server#235]

**Comment by han-gyeong** [comment]
category_International 에서 'KR', 'EN' 이 'KR\n', 'EN\n' 과 같이 개행이 포함되어 저장되어 있어서 값 업데이트 수행했습니다~
(마이그레이션에서 이슈가 있었던 것으로 보입니다)
