### ISSUE TITLE
GCP Service Account Keys exposed. Fix it ASAP

### ISSUE THREAD

**Issue by Prajwalmithun** [beerlot/beerlot-server#90]
Hi @beerlot-contact @dev-ujin 

Your GCP service account keys are exposed.

PATH to it.
[beerlot-server](https://github.com/beerlot/beerlot-server/tree/490e152b9c5b380b249ab52a88dbeaeda9f158a3)/[beerlot-core](https://github.com/beerlot/beerlot-server/tree/490e152b9c5b380b249ab52a88dbeaeda9f158a3/beerlot-core)/beerlot-dev-363211.json

Your Next Actions
Go to GCP console and delete the service account associated.
Delete this file from the GitHub
For more info please check this official documentation from GCP
https://cloud.google.com/iam/docs/best-practices-for-managing-service-account-keys

**Comment by dev-ujin** [comment]
Hi @Prajwalmithun,

Problem fixed.

Thank you for letting me know.
